
version: '3'

services:
  mongodb:
    image: mongo:latest
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./services/mongodb/database:/data/db
    
    restart: always

  
  backend:
    build: ./services/backend/

    volumes:
      - ./services/downloads:/downloads
    ports: 
        - "6001:5000"
    restart: always

    env_file: .env

  frontend:
    container_name: frontend
    build: ./services/frontend

    restart: always
    
    ports:
        - "3000:3000"

    env_file: .env
  
  apk-downloader:
    build: ./services/apk_downloader/

    volumes:
      - ./services/downloads:/downloads
      - ./services/videos:/usr/src/app/videos

    restart: always

    env_file: .env
  
  version-scraper:
    build: ./services/version_scraper/
      
    restart: always

    env_file: .env